services:
  retroarch:
    image: lscr.io/linuxserver/retroarch
    container_name: retroarch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/2000/container-mounts/retroarch/config:/config
      - /mnt/22TB/container-mounts/secure-webtop/downloads/mame:/mame:ro
    shm_size: "1gb"
    networks:
      - retroarch-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute, video, graphics, utility]
    labels:
      # For homepage
      - homepage.group=Desktop Apps
      - homepage.name=retroarch
      - homepage.weight=120
      - homepage.icon=/icons/retroarch.ico
      - homepage.href=https://retroarch.${TS_DOMAIN}
    healthcheck:
      test: 'curl --fail http://localhost:3000/manifest.json 2>/dev/null | grep -o "RetroArch" || exit 1'
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
  ts:
    container_name: retroarch-ts
    image: tailscale/tailscale
    environment:
      - TS_HOSTNAME=retroarch
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - retroarch-net
    depends_on:
      retroarch:
        condition: service_healthy
networks:
  retroarch-net:
